# Generated by Django 3.2.3 on 2021-08-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_x', models.IntegerField(null=True)),
                ('size_y', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Galaxies',
            },
        ),
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_x', models.IntegerField(null=True)),
                ('position_y', models.IntegerField(null=True)),
                ('galaxy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universe.galaxy')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diameter', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=100)),
                ('star_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universe.starsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diameter', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=100)),
                ('live', models.BooleanField(null=True)),
                ('star_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universe.starsystem')),
            ],
        ),
    ]
