# Generated by Django 3.2.3 on 2021-07-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galaxy',
            options={'verbose_name_plural': 'Galaxies'},
        ),
    ]
