# Generated by Django 3.2.3 on 2021-07-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_alter_galaxy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='size_x',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
