# Generated by Django 3.2.3 on 2021-07-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0005_galaxy_size_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='diameter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='live',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='diameter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='starsystem',
            name='position_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='starsystem',
            name='position_y',
            field=models.IntegerField(null=True),
        ),
    ]
